name: DevSecOps Juice Shop Pipeline

on:
  push:
    branches: master

jobs:
  devsecops:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

  #Github token
    - name: Login to GHCR
  uses: docker/login-action@v3
  with:
    registry: ghcr.io
    username: ${{ github.actor }}
    password: ${{ secrets.GITHUB_TOKEN }}

    #Build Docker
    - name: Build Docker image
      run: docker build -t juice-shop-devsecops .

    #Tests unitaires
    - name: Run unit tests
      run: |
        npm install
        npm test || true

    #SAST - Semgrep
    - name: Run Semgrep
      uses: returntocorp/semgrep-action@v1

    #Docker Image Scan
    - name: Trivy Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: juice-shop-devsecops
        severity: HIGH,CRITICAL

    #Run container for DAST
    - name: Run Juice Shop
      run: docker run -d -p 3000:3000 juice-shop-devsecops

    #DAST - OWASP ZAP
    - name: OWASP ZAP Baseline
      uses: zaproxy/action-baseline@v0.9.0
      with:
        target: http://localhost:3000
